version: '3.4'

services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"

  redis_image:
    image: redis
    container_name: cache
    ports:
      - "6379:6379"