version: '3.4'

services:
  notificationsystem:
    build: 
      context: src/WebApi
    restart: always
    environment:
      - ASPNETCORE_URLS=http://+:8000
 
  proxy:
    build: nginx
    ports:
      - 80:80
    depends_on: 
      - notificationsystem